### ISSUE TITLE
Adding an already deleted node port to service shows already acquired error

### ISSUE THREAD

**Issue by hello2mao** [hello2mao/issue-track#1]
https://github.com/kubernetes/kubernetes/issues/32987

**Comment by hello2mao** [comment]
# Reproduce:
## Service type: NodePort
(1)nginx-nodeport-deployment.yaml
```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```
(2)nginx-nodeport-svc.yaml
```yaml
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: nginx-port
    port: 80
    nodePort: 30080
    targetPort: 80
    protocol: TCP
```
(3)k create -f nginx-nodeport-deployment.yaml
(4)k create -f nginx-nodeport-svc.yaml && k get svc
```shell
NAME                TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
kubernetes       ClusterIP     172.18.0.1           <none>             443/TCP             35d
nginx-service   NodePort    172.18.119.85     <none>             80:30080/TCP   22s
```
(5)k delete svc nginx-service && k get svc && k create -f nginx-nodeport-svc.yaml
```shell
service "nginx-service" deleted
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   172.18.0.1   <none>        443/TCP   35d
The Service "nginx-service" is invalid: spec.ports[0].nodePort: Invalid value: 30080: provided port is already allocated
```
